# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ESRM_SierraWeather', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='recordNum',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
